spring:
  main:
    allow-circular-references: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/sync-service-order-db
    username: postgres
    password: postgres
    hikari:
      schema: sync_service_order_schema
      connection-timeout: 10000
  kafka:
    bootstrap-servers: kafka:9092


server:
  port: 8082


app:
  jwt:
    secret: "jwtSecret"
    tokenExpiration: 60m
    refreshTokenExpiration: 480m

logging:
  exception-conversion-word:
    packaging-data: false

