spring:
  data:
    redis:
      host: redis
      port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://postgres:5432/sync-service-user-db
    username: postgres
    password: postgres
    hikari:
      schema: sync_service_user_schema
      connection-timeout: 10000
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 1800000

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  jwt:
    secret: "jwtSecret"
    tokenExpiration: 60m
    refreshTokenExpiration: 10080m
  kafka:
    kafkaMessageGroupId: "user-message-group-id"

server:
  port: 8081